Repository AWS-Cloud-School-6/AIWA-MCP-Backend-MemberService, pull requests merged in 2024-11, with the labels that each got.

#13 #12 Feat: S3 Company-Specific Directing
  src/main/java/AIWA/MCPBackend_Member/Controller/MemberController.java
  src/main/java/AIWA/MCPBackend_Member/Dto/CompanyDto.java
  src/main/java/AIWA/MCPBackend_Member/Service/member/MemberService.java
  src/main/java/AIWA/MCPBackend_Member/Service/s3/S3Service.java
Labels: enhancement

#15 #14 Fix: Roll Back
  src/main/java/AIWA/MCPBackend_Member/Controller/MemberController.java
  src/main/java/AIWA/MCPBackend_Member/Service/member/MemberService.java
  src/main/java/AIWA/MCPBackend_Member/Service/s3/S3Service.java
Labels: fix

#17 16 feat member keyclass
  src/main/java/AIWA/MCPBackend_Member/Controller/MemberController.java
  src/main/java/AIWA/MCPBackend_Member/Dto/AddAwsAndGcpKeyRequestDto.java
  src/main/java/AIWA/MCPBackend_Member/Dto/AiwaKeyResponseDto.java
  src/main/java/AIWA/MCPBackend_Member/Dto/CompanyDto.java
  src/main/java/AIWA/MCPBackend_Member/Dto/DeleteKeyRequestDto.java
  src/main/java/AIWA/MCPBackend_Member/Dto/MemberCredentialDTO.java
  src/main/java/AIWA/MCPBackend_Member/Dto/MemberDeleteRequestDto.java
  src/main/java/AIWA/MCPBackend_Member/Dto/MemberRequestDto.java
  src/main/java/AIWA/MCPBackend_Member/Dto/MemberResponseDto.java
  src/main/java/AIWA/MCPBackend_Member/Entity/AiwaKey.java
  src/main/java/AIWA/MCPBackend_Member/Entity/Member.java
  src/main/java/AIWA/MCPBackend_Member/Service/member/MemberService.java
  src/main/java/AIWA/MCPBackend_Member/Service/s3/S3Service.java
Labels: bug, enhancement, fix
